name: shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: string
        run: echo "Welcome to suneeltesthub1234!"
      - name: mutiline branch
        run:
          node -v
          npm -v